### ISSUE TITLE
Microsoft edX: DAT227x - Developing Business Applications with Microsoft PowerApps, CDS, and Flow  

### ISSUE THREAD

**Issue by nicholasdbrady** [SeaDude/seattlePowerAppers#1]
https://courses.edx.org/courses/course-v1:Microsoft+DAT227x+3T2018/course/

**Comment by SeaDude** [comment]
Hi Nick. Thanks for attending last nights Seattle PowerAppers Meetup group and for the EdX link. I've added it to the list of resources.
