### ISSUE TITLE
InvalidTemplate - Seems to be an array problem

### ISSUE THREAD

**Issue by nicholasdbrady** [SeaDude/seattlePowerAppers#2]
InvalidTemplate. Unable to process template language expressions in action 'DEBUG_compare_versions' inputs at line '1' and column '2641': 'The template language expression 'body('GET_last_release_tag')[0]['name']' cannot be evaluated because array index '0' cannot be selected from empty array. Please see https://aka.ms/logicexpressions for usage details.'.

![image](https://user-images.githubusercontent.com/18353756/79619861-f1628d80-80c2-11ea-9fb0-af20a504ec42.png)

**Comment by nicholasdbrady** [comment]
![image](https://user-images.githubusercontent.com/18353756/79620196-f96efd00-80c3-11ea-9dea-70a251d00220.png)

Where the functions are:
Power Apps appVersion: replace(replace(items('FOR_EACH_app')['properties']['appVersion'],'-',''),':','')
Github releaseVersion: body('GET_last_release_tag')[0]['name']

**Comment by SeaDude** [comment]
Hey Nick. Can you expand the previous action (GET Release Tag). See if it has a `name` attribute. Screenshot and show here.

**Comment by nicholasdbrady** [comment]
Sure! Tricky because we get a status 200, but the payload is empty:
![image](https://user-images.githubusercontent.com/18353756/79623511-971cf900-80d1-11ea-95f2-780241bcc97a.png)
![image](https://user-images.githubusercontent.com/18353756/79623496-7eacde80-80d1-11ea-9b63-971cd2975456.png)

**Comment by SeaDude** [comment]
Likely means that your Flow only **partially** ran earlier
  - Likely **didn't write the Release Tag to the repo**. This action can be found:
    - In the last action in the 404 (new repo) branch of the Flow AND
    - In the last action of the "write diffs" branch of the Flow

Delete the repo from Github and rerun the Flow twice. Once to create the new repo with all source, then again to get through the action you reported the issue on.

**Comment by SeaDude** [comment]
PS: Glad to see someone actually _using_ this flow :)

**Comment by nicholasdbrady** [comment]
Excellent, deleted all repositories. Resubmitting... will check it out from there.
Yeah, noticed my code diffs never uploaded even from our Meetup when we walked through it.
Happy to use it and thanks for all your hard work to make it easy for all of us power addicts / Seattle Power Appers!!

**Comment by nicholasdbrady** [comment]
Hey Eric, I gave it a shot. The first run was 404 (of course), because there were no repositories that existed before. The subsequent run received the 200 status like before, but with an empty JSON body.

**Comment by nicholasdbrady** [comment]
Found one last SeaDude in the 404 status switch. Deleting repositories and trying again :-)

**Comment by nicholasdbrady** [comment]
New error! Progress:
:-)
![GitHub_PA_422](https://user-images.githubusercontent.com/18353756/79678146-129fa880-81ad-11ea-98b7-324f69de9abc.png)

**Comment by SeaDude** [comment]
[Here](https://github.com/SeaDude/seattlePowerAppers/blob/master/flows/knownGood_20200422050652.zip) is a link to a knownGood version. Its been running without issue in my tenant for a while:
![image](https://user-images.githubusercontent.com/8636973/79943031-bf339180-841c-11ea-8b32-bf103dc27650.png)
* Put your Github token in the `SECRETS` Tracked Property
![image](https://user-images.githubusercontent.com/8636973/79943361-8a740a00-841d-11ea-9440-56b6e3fa122b.png)
* Enter your Github username in the `SET varUsername` action
![image](https://user-images.githubusercontent.com/8636973/79943384-9fe93400-841d-11ea-974b-83b9ef43c697.png)

**Comment by nicholasdbrady** [comment]
Trying it Sunday. Will update you on the results :-)

**Comment by nicholasdbrady** [comment]
I believe my issue(s) stems from a data policy assigned to my environment where GitHub is not treated as a business connector. I will close this issue and reopen if this exception does not fix the issue.

**Comment by nicholasdbrady** [comment]
Yo Eric, hope you and your family are well.

I wanted to circle back on my commitment to addressing what the problem was.

It turns out a default data policy in my environment was preventing me from using the GitHub connector with business data.

Long story short, I applied for an exception. I was granted aforementioned exception. Low and behold, it's working! 😊

**Comment by SeaDude** [comment]
Thanks for closing the loop Nick. Thats good information to know. Glad its working for you now. Chat soon.
